2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Configure stats pid to 1336
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Loading settings from /Users/matteo/.config/wandb/settings
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Loading settings from /Users/matteo/Documents/MSc/Period5/DL2/Project/Confidently_Exiting/src/wandb/settings
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-19 23:29:30,937 WARNING MainThread:1336 [wandb_setup.py:_flush():76] Could not find program at -m run_summarization
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m run_summarization'}
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-19 23:29:30,937 INFO    MainThread:1336 [wandb_init.py:_log_setup():521] Logging user logs to /Users/matteo/Documents/MSc/Period5/DL2/Project/Confidently_Exiting/src/wandb/run-20240519_232930-ckaoe2bf/logs/debug.log
2024-05-19 23:29:30,938 INFO    MainThread:1336 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/matteo/Documents/MSc/Period5/DL2/Project/Confidently_Exiting/src/wandb/run-20240519_232930-ckaoe2bf/logs/debug-internal.log
2024-05-19 23:29:30,938 INFO    MainThread:1336 [wandb_init.py:init():561] calling init triggers
2024-05-19 23:29:30,938 INFO    MainThread:1336 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'dataset': 'samsum', 'model': 'jvelja/t5-samsum', 'exit_conf_type': 'JSD_contrastive_confidence', 'exit_conf_threshold': 0.9, 'exit_min_layer': 12, 'type_vocab_reduct': 'None'}
2024-05-19 23:29:30,938 INFO    MainThread:1336 [wandb_init.py:init():611] starting backend
2024-05-19 23:29:30,938 INFO    MainThread:1336 [wandb_init.py:init():615] setting up manager
2024-05-19 23:29:30,944 INFO    MainThread:1336 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-19 23:29:30,945 INFO    MainThread:1336 [wandb_init.py:init():623] backend started and connected
2024-05-19 23:29:30,953 INFO    MainThread:1336 [wandb_init.py:init():715] updated telemetry
2024-05-19 23:29:30,972 INFO    MainThread:1336 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-19 23:29:31,385 INFO    MainThread:1336 [wandb_run.py:_on_init():2357] communicating current version
2024-05-19 23:29:31,545 INFO    MainThread:1336 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-19 23:29:31,546 INFO    MainThread:1336 [wandb_init.py:init():799] starting run threads in backend
2024-05-19 23:29:31,766 WARNING MainThread:1336 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 812, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-05-19 23:29:36,363 WARNING MsgRouterThr:1336 [router.py:message_loop():77] message_loop has been closed
